### ISSUE TITLE
remove rapidraker dependency because of java issues

### ISSUE THREAD

**Issue by elizagrames** [elizagrames/litsearchr#17]

**Comment by mschermann** [comment]
Initial code is here: https://github.com/elizagrames/litsearchr/pull/19

it takes roughly 14.25 minutes compared to 14 seconds with rapidraker

**Comment by elizagrames** [comment]
This is fixed in the sandbox version of the package that will be version 0.2.0 when other issues are fixed. rapidraker can still be used but is only a suggested package; it has been replaced by the "fakerake" function.
