### ISSUE TITLE
Error when calling import_results

### ISSUE THREAD

**Issue by kravitz-eli** [elizagrames/litsearchr#25]
I get an error when I run the example code for import_results() from the documentation.

When I run: 
`write.csv(litsearchr::scopus_example,
          paste(tempdir(), "/scopus.csv", sep = ""))

naive_results <- import_results(paste(tempdir(), "/", sep = ""))`

I get the error 

> Error: 'import_results' is not an exported object from 'namespace:synthesisr'

When I look at the source code of import_results, I see it calls synthesisr::import_results
`function (directory = NULL, filename = NULL, save_dataset = FALSE, 
          verbose = TRUE, save_directory = "./") 
{
  df <- synthesisr:::import_results(directory = directory, filename = filename, 
                                   save_dataset = save_dataset, save_directory = save_directory, 
                                   verbose = verbose)
  return(df)
}
`

I am using the most recent version of synthesisr and there is no function (private or public) called import_results.

**Comment by ltwente** [comment]
I have the same issue

**Comment by elizagrames** [comment]
There were updates to synthesisr that weren't reflected in the litsearchr wrapper functions, but this is now fixed in the latest release of litsearchr.
