### ISSUE TITLE
usable_databases() doesn't work 

### ISSUE THREAD

**Issue by lisaminas** [elizagrames/litsearchr#31]
Hi, 
I just started using litsearchr and can not run the first script provided on the example page (https://elizagrames.github.io/litsearchr/introduction_vignette_v010.html): litsearchr::usable_databases(). It seems Rstudio doesn't recognize "usable_databases".
Any suggestions?

Thanks.

**Comment by elizagrames** [comment]
Ah, you'll want to actually follow the vignette for v030 since the package has been updated and that function is now obsolete. I keep the v010 vignette up solely because it is connected to the manuscript associated with the package, sorry for the confusion.

**Comment by lisaminas** [comment]
Thanks for the update. I have imported my reference list from Web of Science in .txt format and when I run " naiveimport <- litsearchr::import_results(directory = search_directory, verbose = TRUE)" I get a message that the file was not found. I also converted the .txt file to .bib and .ris and it doesn't seem litsearchr can read these files neither (Error in synthesisr::read_refs(filename = filename, return_df = TRUE,  : 
  file not found). Do you have any suggestions? As you suggested above I am following v030 vignette example. Thanks.

**Comment by elizagrames** [comment]
This sounds like a problem of the path to the directory where your files are located; it is not the error you would get if they were not readable, but rather that they can't be found. I would suggest double checking that the path to the directory where you have saved your reference list is correct relative to the directory you are working in.

**Comment by lisaminas** [comment]
ok that could make sense. This is how I defined my directory etc. (the .txt, .bib, .ris are all in the same "literature" folder):
setwd("C:/_LOCALdata/Geospatial_2020/site/literature")
geospatial_search ="C:/_LOCALdata/Geospatial_2020/site/literature/"
list.files(geospatial_search)
search_directory <- system.file(geospatial_search, package = "synthesisr")
naiveimport <- litsearchr::import_results(directory = search_directory, file = NULL, verbose = TRUE)

What am I missing above?

Thanks

**Comment by elizagrames** [comment]
You actually want to set the search_directory directly to the folder with your search results in it (see code below). The "system.file()" line in the vignette is pointing to a directory of results that I know exists on your computer if the package was installed successfully since it is the demo, but I did not explain that part clearly, sorry.

search_directory <- "C:/_LOCALdata/Geospatial_2020/site/literature/"

**Comment by lisaminas** [comment]
Thanks. It worked. 
I was able to make it up to "taggedkeyword". I am not able to extract keywords using your suggested script. Is it because the keywords don't exist in my database? I got my literature database from WOS in .txt file and when I open it there is no keyword field there. I imported the .txt back to zotero and converted the file to .ris and that is the file I am using. Thanks.

**Comment by elizagrames** [comment]
Yeah, if there are no keywords in your file it won't be able to extract anything; the tagged option is pretty fussy and honestly not that helpful anyways. I would suggest just skipping that bit of code and selecting terms from the raked keywords.
