### ISSUE TITLE
max_n not implemented for method="tagged"

### ISSUE THREAD

**Issue by luketudge** [elizagrames/litsearchr#35]
In `extract_terms()`, the `max_n` argument has no effect when `method="tagged"`.

For example:

```
extract_terms(
  keywords = c(
    "Cross-scale occupancy dynamics and postfire specialist and variation and fire regime",
    "Variation and home-range and Black-backed Woodpecker",
    "Black-backed woodpecker and occupancy and burned and beetle-killed and forests"
  ),
  method = "tagged",
  min_freq=1,
  min_n=2,
  max_n=2
)
```

Still returns "cross-scale occupancy dynamics" among the results despite `max_n=2`.

It looks as though this is because [line 65 of term_selection.R](https://github.com/elizagrames/litsearchr/blob/7cf22cb1e0ee1ef656789ed160c73f45964850b8/R/term_selection.R#L65) is missing a `<=` condition against `max_n`.

**Comment by elizagrames** [comment]
Thank you for finding these issues and fixing them! Absolutely brilliant.

**Comment by luketudge** [comment]
Thanks for responding so quickly. It's great to see that I can already install the updated version and keep working with the package. Thanks!
