### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by lucassyyd** [elizagrames/litsearchr#39]
Hey! My name is Lucas, I'm a Biology student and I'm trying to install 'litesearch' to perform systematic reviews, and an error is happening.

devtools::install_github("elizagrames/litsearchr")
Skipping install of 'litsearchr' from a github remote, the SHA1 (d3c8a6ec) has not changed since last install.
  Use `force = TRUE` to force installation

I'm a beginner in R.
can you help me ?

thanks in advance
Lucas

**Comment by elizagrames** [comment]
That means you've already installed the package, so now you can load it with `library(litsearchr)` and use the functions.

**Comment by lucassyyd** [comment]
thanks for listening

^^

**Comment by lucassyyd** [comment]
thanks for helping me ^^
