### ISSUE TITLE
Error could not find function "import_results"

### ISSUE THREAD

**Issue by hancha** [elizagrames/litsearchr#54]
Can't import search results error message:
Error in import_results(file = "pubmed-medication-set.nbib") : 
  could not find function "import_results"

Walking myself through the package and got stuck. Did just download. 
Running RStudio 4.2.1 on macOS Monterey 12.4

**Comment by luketudge** [comment]
Hi @hancha did you first install litsearchr? And then did you load it with the command `library(litsearchr)`? Both of those are necessary before you can access the functions inside the litsearchr package. There is some information on how to install and load here: https://luketudge.github.io/litsearchr-tutorial/litsearchr_tutorial.html#Installation
