### ISSUE TITLE
Using GUI to write the Boolean searches

### ISSUE THREAD

**Issue by CathMo** [elizagrames/litsearchr#57]
Hi,

I'm using the GUI for litsearchr. I'm currently trying to write the boolean search but it won't work. I have no clue on how to code and do not have the time right now to teach myself though I hope to someday. That said, I was hoping someone could help me because I really want to use Eliza's method for my systematic review. 

I have attached a screenshot of the error message. It does not seem to regroup my terms as it should and then clicking the preview searches button, the red message appears at the end of the list. 

I am so grateful for anyone that could help me!

Thanks a lot

Catherine 

<img width="898" alt="Capture d’écran, le 2023-07-13 à 10 52 43" src="https://github.com/elizagrames/litsearchr/assets/139479570/8f786517-6862-4a69-88ea-b360d2b1b988">

**Comment by elizagrames** [comment]
I'm not 100% sure since the log files are pretty vague when I checked them, but, I think the issue is likely that you have semicolons instead of commas and the GUI is expecting comma-separated values

**Comment by CathMo** [comment]
Thank you for your rapid answer. I'll check for that even though I previously saved it as UTF-8 comma delimited and from what I just red it is not recommend to do so with Excel. I'll try with Numbers and keep you updated in case it could help. 

Thanks!
